version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=change-me
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm start

